### ISSUE TITLE
Breaks for native forEach

### ISSUE THREAD

**Issue by fresheneesz** [stacktracejs/stacktrace.js#108]
The following throws an error:

```
;[1].forEach(function() {
    stacktrace.get().then(function(trace) {
        console.log("trace: "+trace)
    }).catch(function(e) {
        console.log("Your error sir: "+e)
    })
})
```

The error is:

```
TypeError: Line Number must be a Number
    at Object.StackFrame.setLineNumber (http://localhost:8100/generatedBuild/stackinfo.umd.js:896:23)
    at Object.StackFrame (http://localhost:8100/generatedBuild/stackinfo.umd.js:855:18)
    at Object.<anonymous> (http://localhost:8100/generatedBuild/stackinfo.umd.js:747:24)
    at Array.map (native)
    at Object.ErrorStackParser$$parseV8OrIE [as parseV8OrIE] (http://localhost:8100/generatedBuild/stackinfo.umd.js:743:53)
    at Object.ErrorStackParser$$parse [as parse] (http://localhost:8100/generatedBuild/stackinfo.umd.js:717:29)
    at Object.<anonymous> (http://localhost:8100/generatedBuild/stackinfo.umd.js:3807:52)
    at $$$internal$$initializePromise (http://localhost:8100/generatedBuild/stackinfo.umd.js:1275:9)
    at new $$es6$promise$promise$$Promise 
```

Its having trouble parsing the `    at Array.forEach (native)` part in this Chrome stack trace string:

```
"Error
    at Object.StackTrace$$get [as get] (http://localhost:8100/generatedBuild/stackinfo.umd.js:3788:23)
    at http://localhost:8100/generatedBuild/stackinfo.umd.js:3898:16
    at Array.forEach (native)
    at Object.21../exceptionMode (http://localhost:8100/generatedBuild/stackinfo.umd.js:3897:6)
    at s (http://localhost:8100/generatedBuild/stackinfo.umd.js:1:516)
    at e (http://localhost:8100/generatedBuild/stackinfo.umd.js:1:687)
    at http://localhost:8100/generatedBuild/stackinfo.umd.js:1:705
    at a (http://localhost:8100/generatedBuild/stackinfo.umd.js:1:247)
    at http://localhost:8100/generatedBuild/stackinfo.umd.js:1:252"
```

**Comment by eriwen** [comment]
@fresheneesz error-stack-parser 1.1.2 has been published which handles this correctly. Please update.

**Comment by mcm-ham** [comment]
I'm getting this error with `StackTrace.fromError` with an error object in an Ember app, here's the stacktrace of the original error object:

```js
TypeError: Cannot read property 'test' of null
    at null.<anonymous> (http://localhost:4200/assets/goodcity.js:1529:17)
    at Descriptor.ComputedPropertyPrototype.get (http://localhost:4200/assets/vendor.js:19770:26)
    at Object.get (http://localhost:4200/assets/vendor.js:25030:19)
    at get (http://localhost:4200/assets/vendor.js:34321:25)
    at null.<anonymous> (http://localhost:4200/assets/vendor.js:34782:29)
    at Array.forEach (native)
    at Object.forEach (http://localhost:4200/assets/vendor.js:21173:30)
    at null.<anonymous> (http://localhost:4200/assets/vendor.js:34778:26)
    at Object.DependentArraysObserver.suspendArrayObservers (http://localhost:4200/assets/vendor.js:34415:16)
    at recompute (http://localhost:4200/assets/vendor.js:34777:36)
```
