### ISSUE TITLE
Problem with stack traces in anonymous functions on firefox

### ISSUE THREAD

**Issue by mtford90** [stacktracejs/stacktrace.js#121]
Hi there,

e.g. with code like:

```
(function () {
   console.log(printStackTrace());
})();
```

On chrome it looks fine:

```
Object.printStackTrace.implementation.createException@http://localhost:8080/vendor.js:36788:22,
Object.printStackTrace.implementation.run@http://localhost:8080/vendor.js:36777:29,
printStackTrace@http://localhost:8080/vendor.js:36764:66,
eval (eval at <anonymous>@http://localhost:8080/bundle.js:47:2), <anonymous>:37:15,
Object.eval (eval at <anonymous>@http://localhost:8080/bundle.js:47:2), <anonymous>:38:3,
code()@http://localhost:8080/bundle.js:47:2,
__webpack_require__@http://localhost:8080/bundle.js:20:30,
(?)()@http://localhost:8080/bundle.js:40:18,
(?)()@http://localhost:8080/bundle.js:43:10
```

On firefox there appears to be a `TypeError` screwing things up:

```
"printStackTrace.implementation.prototype.createException@http://localhost:8080/vendor.js:36788:17,
printStackTrace.implementation.prototype.run@http://localhost:8080/vendor.js:36777:1,
printStackTrace@http://localhost:8080/vendor.js:36764:64,
getSource failed with url: http://localhost:8080/bundle.js line 47 > eval, exception: TypeError: line is undefined()@http://localhost:8080/bundle.js line 47 > eval:37:15,
getSource failed with url: http://localhost:8080/bundle.js line 47 > eval, exception: TypeError: line is undefined()@http://localhost:8080/bundle.js line 47 > eval:36:2,
code()@http://localhost:8080/bundle.js:47:2,
__webpack_require__@http://localhost:8080/bundle.js:20:12,
(?)()@http://localhost:8080/bundle.js:40:18,
(?)()@http://localhost:8080/bundle.js:1:1"
```

This is on firefox 38.0.1

**Comment by mtford90** [comment]
Actually I can't replicate this from within the JS console, maybe it's something to do with the way i'm bundling code, will investigate

**Comment by eriwen** [comment]
Closing due to inactivity. Please reopen with a bit more info if anyone has interest.
